dist: xenial
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements/dev-requirements.txt

script:
  - coverage run -m unittest discover -s tests
  
after_success:
  - coverage report

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
keep_history: true
on:
  branch: master