dist: xenial
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements/dev-requirements.txt

script:
  - coverage run -m unittest discover -s tests
  - coverage report
  